# config.yaml
# This file centralizes all system configurations for the HyperEventGraph project.

# --- Database Configuration ---
database:
  path: "master_state.db"

# --- LLM Provider and Model Routing Configuration ---
# The system uses a unified LLM client that routes tasks to different models
# based on this configuration. API keys should preferably be set as environment
# variables (e.g., DEEPSEEK_API_KEY, MOONSHOT_API_KEY) for security.
llm:
  providers:
    deepseek:
      base_url: "https://api.deepseek.com/v1"
      # API key can be set here directly or via the DEEPSEEK_API_KEY env var.
      # api_key: "sk-your-deepseek-key"
    kimi:
      base_url: "https://api.moonshot.cn/v1"
      # API key can be set here directly or via the MOONSHOT_API_KEY env var.
      # api_key: "sk-your-moonshot-key"

  models:
    # Model to use for the initial triage of raw text.
    triage:
      provider: "kimi"
      name: "moonshot-v1-8k"

    # Model to use for generating a new JSON schema from text samples.
    schema_generation:
      provider: "kimi"
      name: "moonshot-v1-128k"

    # Model to use for extracting structured data based on a schema.
    extraction:
      provider: "deepseek"
      name: "deepseek-coder"

# --- Workflow Specific Configurations ---
review_workflow:
  # Path for the CSV file generated for human review.
  review_csv: "output/review/review_sheet.csv"

learning_workflow:
  # Path to the central JSON file where learned schemas are stored.
  schema_registry_path: "output/schemas/event_schemas.json"
  # Distance threshold for clustering similar texts. Lower is stricter.
  cluster_distance_threshold: 1.4

extraction_workflow:
  # Path for the final output file containing structured event data.
  output_file: "output/extraction/structured_events.jsonl"