# HyperEventGraph Project Configuration

# --- Path Settings ---
# Centralized path management to ensure consistency across all scripts.
paths:
  # Source data before any processing
  raw_data_input: "IC_data/filtered_data.json"
  
  # Main database for tracking the state of each data point
  master_state_db: "database/master_state.db"
  
  # Directory for all script outputs
  output_dir: "output"
  
  # Directory for storing generated schemas or other learned artifacts
  learning_artifacts: "learning"
  
  # Location of the event schema definitions
  schema_registry: "src/event_extraction/schemas.py"

# --- Processing Settings ---
# Parameters controlling how data is processed in batches.
processing:
  # Number of items to process in a single run of a batch script
  batch_size: 200
  
  # Maximum number of items to process in the learning workflow
  learning_batch_size: 50

# --- Model Settings ---
# Configuration for the Large Language Models used in different agents.
models:
  # Model for the initial triage phase (fast and cheap)
  triage_model: "moonshot-v1-8k"
  
  # Model for the more complex extraction and analysis tasks
  extraction_model: "moonshot-v1-32k"
  
  # Model used by the SchemaLearnerAgent for pattern induction
  learning_model: "moonshot-v1-128k"
  
  # API endpoint configuration
  api_base_url: "https://api.siliconflow.cn/v1"

# --- Logging Settings ---
# Controls the verbosity of logs across the application.
logging:
  # Log level (e.g., DEBUG, INFO, WARNING, ERROR)
  level: "INFO"
  
  # Path to the main log file
  log_file: "logs/app.log"

# --- Database Settings ---
# Configuration for the master state database.
database:
  # Type of the database (currently only sqlite is supported)
  type: "sqlite"
  
  # Timeout for database connections in seconds
  timeout: 10
