# HyperEventGraph 数据库配置文件
# 配置ChromaDB和Neo4j的详细连接参数和性能设置

# Neo4j 图数据库配置
neo4j:
  # 连接配置
  connection:
    uri: "bolt://localhost:7687"
    username: "neo4j"
    password: "password"
    database: "neo4j"  # 默认数据库名
    
  # 连接池配置
  pool:
    max_connection_lifetime: 3600  # 连接最大生存时间(秒)
    max_connection_pool_size: 50   # 最大连接池大小
    connection_acquisition_timeout: 60  # 连接获取超时(秒)
    
  # 事务配置
  transaction:
    timeout: 30  # 事务超时时间(秒)
    retry_attempts: 3  # 重试次数
    retry_delay: 1.0  # 重试延迟(秒)
    
  # 查询优化
  query:
    fetch_size: 1000  # 批量查询大小
    max_query_time: 30  # 最大查询时间(秒)
    enable_query_cache: true
    cache_size: 1000  # 查询缓存大小
    
  # 索引配置
  indexes:
    # 事件节点索引
    event_indexes:
      - property: "event_id"
        type: "btree"
      - property: "event_type"
        type: "btree"
      - property: "timestamp"
        type: "btree"
      - property: "title"
        type: "fulltext"
        
    # 关系索引
    relation_indexes:
      - property: "relation_type"
        type: "btree"
      - property: "confidence"
        type: "btree"
        
  # 性能监控
  monitoring:
    enable_metrics: true
    metrics_interval: 60  # 指标收集间隔(秒)
    slow_query_threshold: 5.0  # 慢查询阈值(秒)
    
# ChromaDB 向量数据库配置
chromadb:
  # 连接配置
  connection:
    host: "localhost"
    port: 8000
    # 持久化路径(本地模式)
    persist_directory: "./data/chroma_db"
    # 客户端模式: "local" 或 "http"
    client_mode: "local"
    
  # HTTP客户端配置(当client_mode为http时)
  http_client:
    timeout: 30  # 请求超时(秒)
    max_retries: 3  # 最大重试次数
    retry_delay: 1.0  # 重试延迟(秒)
    
  # 集合配置
  collections:
    # 事件向量集合
    events:
      name: "event_vectors"
      metadata_fields:
        - "event_id"
        - "event_type"
        - "timestamp"
        - "source"
      distance_function: "cosine"  # cosine, l2, ip
      
    # 模式向量集合
    patterns:
      name: "pattern_vectors"
      metadata_fields:
        - "pattern_id"
        - "pattern_type"
        - "frequency"
        - "confidence"
      distance_function: "cosine"
      
    # 关系向量集合
    relations:
      name: "relation_vectors"
      metadata_fields:
        - "relation_id"
        - "relation_type"
        - "source_event"
        - "target_event"
      distance_function: "cosine"
      
  # 向量检索配置
  retrieval:
    default_n_results: 10  # 默认返回结果数
    max_n_results: 100     # 最大返回结果数
    similarity_threshold: 0.7  # 相似度阈值
    
  # 批量操作配置
  batch:
    insert_batch_size: 1000  # 批量插入大小
    query_batch_size: 100    # 批量查询大小
    max_concurrent_batches: 5  # 最大并发批次
    
  # 缓存配置
  cache:
    enable_vector_cache: true
    vector_cache_size: 10000  # 向量缓存大小
    cache_ttl: 3600  # 缓存生存时间(秒)
    
  # 性能监控
  monitoring:
    enable_metrics: true
    metrics_interval: 60  # 指标收集间隔(秒)
    slow_query_threshold: 2.0  # 慢查询阈值(秒)
    
# 数据同步配置
synchronization:
  # 双数据库同步
  dual_db_sync:
    enable: true
    sync_interval: 300  # 同步检查间隔(秒)
    conflict_resolution: "neo4j_priority"  # 冲突解决策略
    
  # 数据一致性检查
  consistency_check:
    enable: true
    check_interval: 3600  # 一致性检查间隔(秒)
    auto_repair: true  # 自动修复不一致
    
  # 备份配置
  backup:
    enable: true
    backup_interval: 86400  # 备份间隔(秒，24小时)
    backup_retention: 7  # 备份保留天数
    backup_path: "./backups"
    
# 集群配置(生产环境)
cluster:
  # Neo4j集群
  neo4j_cluster:
    enable: false
    nodes:
      - uri: "bolt://neo4j-node1:7687"
        role: "leader"
      - uri: "bolt://neo4j-node2:7687"
        role: "follower"
      - uri: "bolt://neo4j-node3:7687"
        role: "follower"
    load_balancing: "round_robin"  # round_robin, least_connections
    
  # ChromaDB集群
  chroma_cluster:
    enable: false
    nodes:
      - host: "chroma-node1"
        port: 8000
      - host: "chroma-node2"
        port: 8000
      - host: "chroma-node3"
        port: 8000
    load_balancing: "round_robin"
    
# 安全配置
security:
  # SSL/TLS配置
  ssl:
    enable: false
    cert_file: "/path/to/cert.pem"
    key_file: "/path/to/key.pem"
    ca_file: "/path/to/ca.pem"
    
  # 访问控制
  access_control:
    enable_auth: false
    api_key: "your-api-key"
    allowed_hosts:
      - "localhost"
      - "127.0.0.1"
      
# 开发环境配置
development:
  # 调试模式
  debug:
    enable: true
    log_queries: true
    log_performance: true
    
  # 测试数据
  test_data:
    auto_load: true
    sample_size: 100
    
# 生产环境配置
production:
  # 性能优化
  performance:
    enable_compression: true
    enable_connection_pooling: true
    max_memory_usage: "8GB"
    
  # 监控告警
  alerting:
    enable: true
    alert_thresholds:
      cpu_usage: 80  # CPU使用率阈值(%)
      memory_usage: 85  # 内存使用率阈值(%)
      disk_usage: 90  # 磁盘使用率阈值(%)
      query_latency: 5.0  # 查询延迟阈值(秒)
      
# 扩展配置
extensions:
  # 自定义插件
  plugins:
    enable: false
    plugin_directory: "./plugins"
    
  # 第三方集成
  integrations:
    elasticsearch:
      enable: false
      host: "localhost"
      port: 9200
      
    redis:
      enable: false
      host: "localhost"
      port: 6379
      db: 0
      
    kafka:
      enable: false
      bootstrap_servers:
        - "localhost:9092"
      topic_prefix: "hypereventgraph"